version: "3"
services:
  postgres:
    image: postgres:11.3
    container_name: project_db
    ports:
      - "4432:5432"
    environment:
      - POSTGRES_PASSWORD=secretpw
      - POSTGRES_USER=klaus
      - POSTGRES_DB=project_db
    volumes:
      - ./init-project-db.sql:/docker-entrypoint-initdb.d/init-project-db.sql
      - ./db-data:/var/lib/postgresql/data
  nginx:
    image: nh/nginx
    build:
      context: nginx
    container_name: nginx_proxy
    ports:
      - "4088:4088"
